In [1]:
import pandas as pd

bucket='soccer-analytics-bucket'
data_key = 'PL_19:20.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_19 = pd.read_csv(data_location)
PL_data_19 = PL_data_19[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
bucket='soccer-analytics-bucket'
data_key = 'Premier League/PL_18:19.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_18 = pd.read_csv(data_location)
PL_data_18 = PL_data_18[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]

bucket='soccer-analytics-bucket'
data_key = 'Premier League/PL_17:18.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_17 = pd.read_csv(data_location)
PL_data_17 = PL_data_17[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]

bucket='soccer-analytics-bucket'
data_key = 'Premier League/PL_16:17.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_16 = pd.read_csv(data_location)
PL_data_16 = PL_data_16[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]


bucket='soccer-analytics-bucket'
data_key = 'Premier League/PL_15:16.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_15 = pd.read_csv(data_location)
PL_data_15 = PL_data_15[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]

bucket='soccer-analytics-bucket'
data_key = 'Premier League/PL_14:15.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_14 = pd.read_csv(data_location)
PL_data_14 = PL_data_14[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]

bucket='soccer-analytics-bucket'
data_key = 'Premier League/PL_13:14.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_13 = pd.read_csv(data_location)
PL_data_13 = PL_data_13[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]


bucket='soccer-analytics-bucket'
data_key = 'Premier League/PL_12:13.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_12 = pd.read_csv(data_location)
PL_data_12 = PL_data_12[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]


bucket='soccer-analytics-bucket'
data_key = 'Premier League/PL_11:12.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_11 = pd.read_csv(data_location)
PL_data_11 = PL_data_11[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]


bucket='soccer-analytics-bucket'
data_key = 'Premier League/PL_10:11.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_10 = pd.read_csv(data_location)
PL_data_10 = PL_data_10[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]


bucket='soccer-analytics-bucket'
data_key = 'Premier League/PL_09:10.csv'
data_location = 's3://{}/{}'.format(bucket, data_key)

PL_data_09 = pd.read_csv(data_location)
PL_data_09 = PL_data_09[['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA','WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']]

In [4]:
PL_data_19.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,WHH,WHD,WHA,VCH,VCD,VCA
0,E0,09/08/2019,Liverpool,Norwich,4,1,H,4,0,H,M Oliver,15,12,7,5,9,9,11,2,0,2,0,0,1.14,10.00,19.00,1.14,8.25,18.50,1.15,8.00,18.00,1.12,8.5,21.00,1.14,9.5,23.00
1,E0,10/08/2019,West Ham,Man City,0,5,A,0,1,A,M Dean,5,14,3,9,6,13,1,1,2,2,0,0,12.00,6.50,1.22,11.50,5.75,1.26,11.00,6.10,1.25,13.00,6.0,1.24,12.00,6.5,1.25
2,E0,10/08/2019,Bournemouth,Sheffield United,1,1,D,0,0,D,K Friend,13,8,3,3,10,19,3,4,2,1,0,0,1.95,3.60,3.60,1.95,3.60,3.90,1.97,3.55,3.80,2.00,3.5,3.80,2.00,3.6,4.00
3,E0,10/08/2019,Burnley,Southampton,3,0,H,0,0,D,G Scott,10,11,4,3,6,12,2,7,0,0,0,0,2.62,3.20,2.75,2.65,3.20,2.75,2.65,3.20,2.75,2.70,3.2,2.75,2.70,3.3,2.80
4,E0,10/08/2019,Crystal Palace,Everton,0,0,D,0,0,D,J Moss,6,10,2,3,16,14,6,2,2,1,0,1,3.00,3.25,2.37,3.20,3.20,2.35,3.10,3.20,2.40,3.10,3.3,2.35,3.20,3.3,2.45

In [5]:
PL_data_19.shape

(288, 38)

In [6]:
PL_data_18.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,WHH,WHD,WHA,VCH,VCD,VCA
0,E0,10/08/2018,Man United,Leicester,2,1,H,1,0,H,A Marriner,8,13,6,4,11,8,2,5,2,1,0,0,1.57,3.9,7.50,1.53,4.0,7.50,1.55,3.80,7.00,1.57,3.8,6.00,1.57,4.0,7.00
1,E0,11/08/2018,Bournemouth,Cardiff,2,0,H,1,0,H,K Friend,12,10,4,1,11,9,7,4,1,1,0,0,1.90,3.6,4.50,1.90,3.4,4.40,1.90,3.50,4.10,1.91,3.5,4.00,1.87,3.6,4.75
2,E0,11/08/2018,Fulham,Crystal Palace,0,2,A,0,1,A,M Dean,15,10,6,9,9,11,5,5,1,2,0,0,2.50,3.4,3.00,2.45,3.3,2.95,2.40,3.30,2.95,2.45,3.3,2.80,2.50,3.4,3.00
3,E0,11/08/2018,Huddersfield,Chelsea,0,3,A,0,2,A,C Kavanagh,6,13,1,4,9,8,2,5,2,1,0,0,6.50,4.0,1.61,6.25,3.9,1.57,6.20,4.00,1.55,5.80,3.9,1.57,6.50,4.0,1.62
4,E0,11/08/2018,Newcastle,Tottenham,1,2,A,1,2,A,M Atkinson,15,15,2,5,11,12,3,5,2,2,0,0,3.90,3.5,2.04,3.80,3.5,2.00,3.70,3.35,2.05,3.80,3.2,2.05,3.90,3.4,2.10

In [7]:
PL_data_18.shape

(380, 38)

In [8]:
print (PL_data_19.shape)
print (PL_data_18.shape)
print (PL_data_17.shape)
print (PL_data_16.shape)
print (PL_data_15.shape)
print (PL_data_14.shape)
print (PL_data_13.shape)
print (PL_data_12.shape)
print (PL_data_11.shape)
print (PL_data_10.shape)
print (PL_data_09.shape)

(288, 38)
(380, 38)
(380, 38)
(380, 38)
(380, 38)
(381, 38)
(380, 38)
(380, 38)
(380, 38)
(380, 38)
(380, 38)

In [9]:
print (PL_data_19.columns)
print (PL_data_18.columns)
print (PL_data_17.columns)
print (PL_data_16.columns)
print (PL_data_15.columns)
print (PL_data_14.columns)
print (PL_data_13.columns)
print (PL_data_12.columns)
print (PL_data_11.columns)
print (PL_data_10.columns)
print (PL_data_09.columns)

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')

In [10]:
frames = [PL_data_19,PL_data_18,PL_data_17,PL_data_16,PL_data_15,PL_data_14,PL_data_13,PL_data_12,PL_data_11,PL_data_10,PL_data_09]

pl_data = pd.concat(frames)

In [11]:
pl_data.shape

(4089, 38)

In [12]:
pl_data.isnull().sum()

Div         1
Date        1
HomeTeam    1
AwayTeam    1
FTHG        1
FTAG        1
FTR         1
HTHG        1
HTAG        1
HTR         1
Referee     1
HS          1
AS          1
HST         1
AST         1
HF          1
AF          1
HC          1
AC          1
HY          1
AY          1
HR          1
AR          1
B365H       1
B365D       1
B365A       1
BWH         2
BWD         2
BWA         2
IWH         2
IWD         2
IWA         2
WHH         1
WHD         1
WHA         1
VCH         1
VCD         1
VCA         1
dtype: int64

In [13]:
pl_data = pl_data.dropna()

In [14]:
pl_data.shape

(4086, 38)

In [15]:
pl_data.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,WHH,WHD,WHA,VCH,VCD,VCA
0,E0,09/08/2019,Liverpool,Norwich,4.0,1.0,H,4.0,0.0,H,M Oliver,15.0,12.0,7.0,5.0,9.0,9.0,11.0,2.0,0.0,2.0,0.0,0.0,1.14,10.00,19.00,1.14,8.25,18.50,1.15,8.00,18.00,1.12,8.5,21.00,1.14,9.5,23.00
1,E0,10/08/2019,West Ham,Man City,0.0,5.0,A,0.0,1.0,A,M Dean,5.0,14.0,3.0,9.0,6.0,13.0,1.0,1.0,2.0,2.0,0.0,0.0,12.00,6.50,1.22,11.50,5.75,1.26,11.00,6.10,1.25,13.00,6.0,1.24,12.00,6.5,1.25
2,E0,10/08/2019,Bournemouth,Sheffield United,1.0,1.0,D,0.0,0.0,D,K Friend,13.0,8.0,3.0,3.0,10.0,19.0,3.0,4.0,2.0,1.0,0.0,0.0,1.95,3.60,3.60,1.95,3.60,3.90,1.97,3.55,3.80,2.00,3.5,3.80,2.00,3.6,4.00
3,E0,10/08/2019,Burnley,Southampton,3.0,0.0,H,0.0,0.0,D,G Scott,10.0,11.0,4.0,3.0,6.0,12.0,2.0,7.0,0.0,0.0,0.0,0.0,2.62,3.20,2.75,2.65,3.20,2.75,2.65,3.20,2.75,2.70,3.2,2.75,2.70,3.3,2.80
4,E0,10/08/2019,Crystal Palace,Everton,0.0,0.0,D,0.0,0.0,D,J Moss,6.0,10.0,2.0,3.0,16.0,14.0,6.0,2.0,2.0,1.0,0.0,1.0,3.00,3.25,2.37,3.20,3.20,2.35,3.10,3.20,2.40,3.10,3.3,2.35,3.20,3.3,2.45

In [16]:
pl_data.isnull().sum()

Div         0
Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
Referee     0
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
B365H       0
B365D       0
B365A       0
BWH         0
BWD         0
BWA         0
IWH         0
IWD         0
IWA         0
WHH         0
WHD         0
WHA         0
VCH         0
VCD         0
VCA         0
dtype: int64

In [21]:
from io import StringIO # python3; python2: BytesIO 
import boto3

bucket = 'soccer-analytics-bucket' # already created on S3
csv_buffer = StringIO()
pl_data.to_csv(csv_buffer)
s3_resource = boto3.resource('s3')
s3_resource.Object(bucket, 'pl_data.csv').put(Body=csv_buffer.getvalue())

{'ResponseMetadata': {'RequestId': '1CE4B26A3EB5998B',
  'HostId': 'HFzCR9lq4pY3fCtEUL6DIgZMfGhGct2X7zlh8CUUpWSDY6P2V1/pJ1qm4gUWOoe0coJpydwhRYk=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'HFzCR9lq4pY3fCtEUL6DIgZMfGhGct2X7zlh8CUUpWSDY6P2V1/pJ1qm4gUWOoe0coJpydwhRYk=',
   'x-amz-request-id': '1CE4B26A3EB5998B',
   'date': 'Sun, 03 May 2020 09:52:30 GMT',
   'etag': '"f26bda2657dbc8852abf1510a3ce05a4"',
   'content-length': '0',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'ETag': '"f26bda2657dbc8852abf1510a3ce05a4"'}